import type {
  Trade,
  TradeChatMessage,
  TradeChatRoom,
  TradeEvent,
  TradeInterest,
} from "@/types/trade";
import type { UserReputation } from "@/types/profile";

export const demoUser = {
  uid: "sandbox-user-001",
  username: "lagos_phone_hub",
};

const demoProfiles: Record<string, UserReputation> = {
  pi_buyer_demo: {
    userId: "buyer-user-001",
    piUsername: "pi_buyer_demo",
    verifiedBadge: true,
    payoutReady: true,
    payoutReadinessConfirmedAt: "2026-06-07T08:00:00.000Z",
    successfulTrades: 3,
    disputedTrades: 0,
    cancelledTrades: 1,
    buyCount: 4,
    sellCount: 1,
    trustScore: 94,
  },
  abuja_tradehub: {
    userId: "buyer-user-003",
    piUsername: "abuja_tradehub",
    verifiedBadge: false,
    payoutReady: true,
    payoutReadinessConfirmedAt: "2026-06-07T08:15:00.000Z",
    successfulTrades: 2,
    disputedTrades: 0,
    cancelledTrades: 0,
    buyCount: 3,
    sellCount: 2,
    trustScore: 91,
  },
  portharcourt_pi: {
    userId: "buyer-user-002",
    piUsername: "portharcourt_pi",
    verifiedBadge: false,
    payoutReady: true,
    payoutReadinessConfirmedAt: "2026-06-07T08:30:00.000Z",
    successfulTrades: 1,
    disputedTrades: 1,
    cancelledTrades: 0,
    buyCount: 2,
    sellCount: 0,
    trustScore: 78,
  },
  market_runner: {
    userId: "seller-user-002",
    piUsername: "market_runner",
    verifiedBadge: false,
    verificationRequestedAt: "2026-06-06T19:30:00.000Z",
    payoutReady: true,
    payoutReadinessConfirmedAt: "2026-06-07T09:00:00.000Z",
    successfulTrades: 2,
    disputedTrades: 0,
    cancelledTrades: 0,
    buyCount: 0,
    sellCount: 3,
    trustScore: 90,
  },
};

export const demoTrades: Trade[] = [
  {
    id: "trade-001",
    sellerPiUsername: "lagos_phone_hub",
    sellerUserId: "sandbox-user-001",
    visibility: "public",
    targetBuyerPiUsernames: [],
    title: "Used Android phone barter",
    description:
      "Clean Android phone with charger, battery checked, and screen condition disclosed for in-person inspection.",
    amountTestPi: 42,
    status: "Draft",
    interestCount: 2,
    locationLabel: "Ikeja, Lagos",
    locationArea: "Computer Village",
    deliveryTerms:
      "Seller will meet buyer at the agreed pickup point and share a photo of the packaged device before handoff.",
    createdAt: "2026-06-06T17:00:00.000Z",
    updatedAt: "2026-06-06T17:15:00.000Z",
  },
  {
    id: "trade-002",
    sellerPiUsername: "market_runner",
    sellerUserId: "seller-user-002",
    visibility: "public",
    targetBuyerPiUsernames: [],
    buyerPiUsername: "pi_buyer_demo",
    buyerUserId: "buyer-user-001",
    title: "Groceries delivery bundle",
    description:
      "Public seller offer for a grocery bundle with local delivery.",
    amountTestPi: 8.5,
    status: "PendingFunding",
    selectedInterestId: "interest-003",
    selectedAt: "2026-06-06T16:00:00.000Z",
    selectionExpiresAt: "2026-06-06T16:20:00.000Z",
    interestCount: 1,
    sellerProfile: demoProfiles.market_runner,
    buyerProfile: demoProfiles.pi_buyer_demo,
    locationLabel: "Lekki Phase 1, Lagos",
    locationArea: "Estate gate",
    deliveryTerms:
      "Seller will deliver to the buyer's estate gate and upload a delivery note.",
    createdAt: "2026-06-06T15:30:00.000Z",
    updatedAt: "2026-06-06T16:20:00.000Z",
  },
  {
    id: "trade-005",
    sellerPiUsername: "lagos_phone_hub",
    sellerUserId: "sandbox-user-001",
    visibility: "public",
    targetBuyerPiUsernames: [],
    buyerPiUsername: "abuja_tradehub",
    buyerUserId: "buyer-user-003",
    selectedInterestId: "interest-005",
    selectedAt: "2026-06-06T18:45:00.000Z",
    selectionExpiresAt: "2026-06-06T19:05:00.000Z",
    title: "Funded camera lens handoff",
    description:
      "Used camera lens with courier pickup arranged; seller must upload package proof before dispatch.",
    amountTestPi: 26,
    status: "Funded",
    interestCount: 1,
    buyerProfile: demoProfiles.abuja_tradehub,
    locationLabel: "Maitama, Abuja",
    locationArea: "Courier pickup counter",
    deliveryTerms:
      "Seller uploads package image proof before dispatching through local courier.",
    payment: {
      id: "payment-005",
      tradeId: "trade-005",
      piPaymentId: "pi-demo-payment-005",
      amountTestPi: 26.52,
      sellerAmountTestPi: 26,
      platformFeeTestPi: 0.52,
      buyerTotalTestPi: 26.52,
      buyerPaymentTxid: "demo-fund-trade-005-txid",
      buyerPaymentLink: "https://api.testnet.minepi.com/transactions/demo-fund-trade-005-txid",
      escrowStatus: "held_in_app",
      releaseStatus: "NotStarted",
      createdAt: "2026-06-06T18:59:00.000Z",
      updatedAt: "2026-06-06T19:00:00.000Z",
    },
    createdAt: "2026-06-06T18:30:00.000Z",
    updatedAt: "2026-06-06T19:00:00.000Z",
  },
  {
    id: "trade-003",
    sellerPiUsername: "pi_buyer_demo",
    sellerUserId: "buyer-user-001",
    visibility: "public",
    targetBuyerPiUsernames: [],
    buyerPiUsername: "portharcourt_pi",
    buyerUserId: "buyer-user-002",
    selectedInterestId: "interest-004",
    selectedAt: "2026-06-05T11:25:00.000Z",
    selectionExpiresAt: "2026-06-05T11:45:00.000Z",
    title: "Laptop repair deposit",
    description:
      "Repair deposit for replacement parts; buyer opened a dispute because the uploaded invoice details need review.",
    amountTestPi: 18,
    status: "Disputed",
    interestCount: 1,
    sellerProfile: demoProfiles.pi_buyer_demo,
    buyerProfile: demoProfiles.portharcourt_pi,
    locationLabel: "Port Harcourt, Rivers",
    locationArea: "GRA service desk",
    deliveryProofNote: "Seller uploaded a parts invoice, but the buyer says the serial number does not match.",
    deliveryProofUrl: "https://example.com/piscrow-demo-parts-proof",
    deliveryTerms:
      "Technician must upload photo evidence of the replacement part and repair receipt.",
    payment: {
      id: "payment-003",
      tradeId: "trade-003",
      piPaymentId: "pi-demo-payment-003",
      amountTestPi: 18.36,
      sellerAmountTestPi: 18,
      platformFeeTestPi: 0.36,
      buyerTotalTestPi: 18.36,
      buyerPaymentTxid: "demo-fund-trade-003-txid",
      buyerPaymentLink: "https://api.testnet.minepi.com/transactions/demo-fund-trade-003-txid",
      escrowStatus: "held_in_app",
      releaseStatus: "NotStarted",
      createdAt: "2026-06-05T11:28:00.000Z",
      updatedAt: "2026-06-06T13:00:00.000Z",
    },
    createdAt: "2026-06-05T11:00:00.000Z",
    updatedAt: "2026-06-06T13:00:00.000Z",
  },
  {
    id: "trade-006",
    sellerPiUsername: "market_runner",
    sellerUserId: "seller-user-002",
    visibility: "public",
    targetBuyerPiUsernames: [],
    buyerPiUsername: "lagos_phone_hub",
    buyerUserId: "sandbox-user-001",
    selectedInterestId: "interest-006",
    selectedAt: "2026-06-06T20:10:00.000Z",
    selectionExpiresAt: "2026-06-06T21:10:00.000Z",
    title: "Awaiting release shoe delivery",
    description:
      "Local sneaker delivery already confirmed by the buyer, with both sides waiting for PiScrow to release the held escrow.",
    amountTestPi: 33,
    status: "AwaitingRelease",
    interestCount: 1,
    sellerProfile: demoProfiles.market_runner,
    locationLabel: "Surulere, Lagos",
    locationArea: "Stadium road handoff",
    deliveryTerms:
      "Seller drops package with rider, uploads dispatch proof, and buyer confirms receipt with a doorstep image.",
    deliveryProofNote:
      "Rider accepted the package and shared a dispatch photo before leaving the pickup point.",
    buyerReceiptNote:
      "Buyer received the sneakers and confirmed the pair matches the agreed color and size.",
    payment: {
      id: "payment-006",
      tradeId: "trade-006",
      piPaymentId: "pi-demo-payment-006",
      amountTestPi: 33.66,
      sellerAmountTestPi: 33,
      platformFeeTestPi: 0.66,
      buyerTotalTestPi: 33.66,
      buyerPaymentTxid: "demo-fund-trade-006-txid",
      buyerPaymentLink: "https://api.testnet.minepi.com/transactions/demo-fund-trade-006-txid",
      escrowStatus: "held_in_app",
      releaseStatus: "NotStarted",
      createdAt: "2026-06-06T20:12:00.000Z",
      updatedAt: "2026-06-06T20:30:00.000Z",
    },
    createdAt: "2026-06-06T20:00:00.000Z",
    updatedAt: "2026-06-06T20:30:00.000Z",
  },
  {
    id: "trade-004",
    sellerPiUsername: "market_runner",
    sellerUserId: "seller-user-002",
    visibility: "private",
    targetBuyerPiUsernames: ["lagos_phone_hub"],
    title: "Private spare parts offer",
    description:
      "Private phone spare-parts offer with the target buyer asked to confirm the exact device model before selection.",
    amountTestPi: 15,
    status: "Draft",
    interestCount: 0,
    locationLabel: "Yaba, Lagos",
    locationArea: "Phone accessories lane",
    deliveryTerms:
      "Buyer confirms exact model before seller ships the parts locally.",
    createdAt: "2026-06-06T18:00:00.000Z",
    updatedAt: "2026-06-06T18:00:00.000Z",
  },
];

export const demoInterests: TradeInterest[] = [
  {
    id: "interest-001",
    tradeId: "trade-001",
    buyerUserId: "buyer-user-001",
    buyerPiUsername: "pi_buyer_demo",
    buyerProfile: demoProfiles.pi_buyer_demo,
    responseNote: "I can pay fast and pick up after work today.",
    status: "Declined",
    createdAt: "2026-06-06T16:40:00.000Z",
    updatedAt: "2026-06-06T16:50:00.000Z",
  },
  {
    id: "interest-002",
    tradeId: "trade-001",
    buyerUserId: "buyer-user-003",
    buyerPiUsername: "abuja_tradehub",
    buyerProfile: demoProfiles.abuja_tradehub,
    responseNote: "I need same-day handoff and can meet near the station.",
    status: "Open",
    createdAt: "2026-06-06T16:45:00.000Z",
    updatedAt: "2026-06-06T16:45:00.000Z",
  },
  {
    id: "interest-003",
    tradeId: "trade-002",
    buyerUserId: "buyer-user-004",
    buyerPiUsername: "pi_buyer_demo",
    buyerProfile: demoProfiles.pi_buyer_demo,
    responseNote: "I can confirm gate pickup and handle local delivery.",
    status: "Selected",
    createdAt: "2026-06-06T15:50:00.000Z",
    updatedAt: "2026-06-06T16:00:00.000Z",
  },
  {
    id: "interest-004",
    tradeId: "trade-003",
    buyerUserId: "buyer-user-002",
    buyerPiUsername: "portharcourt_pi",
    buyerProfile: demoProfiles.portharcourt_pi,
    responseNote: "I can pay today but need proof of parts before release.",
    status: "Selected",
    createdAt: "2026-06-05T11:20:00.000Z",
    updatedAt: "2026-06-05T11:25:00.000Z",
  },
  {
    id: "interest-005",
    tradeId: "trade-005",
    buyerUserId: "buyer-user-003",
    buyerPiUsername: "abuja_tradehub",
    buyerProfile: demoProfiles.abuja_tradehub,
    responseNote: "I can receive through local courier and confirm quickly.",
    status: "Selected",
    createdAt: "2026-06-06T18:40:00.000Z",
    updatedAt: "2026-06-06T18:45:00.000Z",
  },
  {
    id: "interest-006",
    tradeId: "trade-006",
    buyerUserId: "sandbox-user-001",
    buyerPiUsername: "lagos_phone_hub",
    responseNote: "I can confirm delivery quickly once the rider arrives.",
    status: "Selected",
    createdAt: "2026-06-06T20:06:00.000Z",
    updatedAt: "2026-06-06T20:10:00.000Z",
  },
];

export const demoEvents: TradeEvent[] = [
  {
    id: "event-001",
    tradeId: "trade-001",
    actor: "lagos_phone_hub",
    eventType: "Seller posted public listing",
    notes: "Seller opened the trade to public interest.",
    createdAt: "2026-06-06T16:00:00.000Z",
  },
  {
    id: "event-002",
    tradeId: "trade-001",
    actor: "pi_buyer_demo",
    eventType: "Interest submitted",
    notes: "Buyer responded with same-day pickup availability.",
    createdAt: "2026-06-06T16:40:00.000Z",
  },
  {
    id: "event-003",
    tradeId: "trade-002",
    actor: "market_runner",
    eventType: "Private offer finalized",
    notes: "Seller limited the listing to selected buyers.",
    createdAt: "2026-06-06T15:35:00.000Z",
  },
  {
    id: "event-004",
    tradeId: "trade-001",
    actor: "lagos_phone_hub",
    eventType: "Buyer selected",
    notes: "Seller chose the buyer response with the best pickup plan.",
    createdAt: "2026-06-06T16:50:00.000Z",
  },
  {
    id: "event-005",
    tradeId: "trade-001",
    actor: "pi_buyer_demo",
    eventType: "Trade funded",
    notes: "Server verified buyer Test Pi payment.",
    createdAt: "2026-06-06T17:15:00.000Z",
  },
  {
    id: "event-006",
    tradeId: "trade-002",
    actor: "market_runner",
    eventType: "Delivery submitted",
    notes: "Seller uploaded delivery note for buyer review.",
    createdAt: "2026-06-06T16:20:00.000Z",
  },
  {
    id: "event-007",
    tradeId: "trade-003",
    actor: "portharcourt_pi",
    eventType: "Dispute opened",
    notes: "Buyer requested admin review before completion.",
    createdAt: "2026-06-06T13:00:00.000Z",
  },
  {
    id: "event-008",
    tradeId: "trade-005",
    actor: "abuja_tradehub",
    eventType: "Payment completed",
    notes: "Buyer funding is held while seller prepares delivery proof.",
    createdAt: "2026-06-06T19:00:00.000Z",
  },
  {
    id: "event-009",
    tradeId: "trade-003",
    actor: "admin",
    eventType: "Admin requested seller follow-up",
    notes: "Admin asked the seller to upload clearer part photos and tracking details before resolution.",
    createdAt: "2026-06-06T13:20:00.000Z",
  },
  {
    id: "event-010",
    tradeId: "trade-003",
    actor: "pi_buyer_demo",
    eventType: "Seller dispute update",
    notes: "Seller replied that the replacement part is ready and will add clearer proof before release.",
    createdAt: "2026-06-06T13:45:00.000Z",
  },
];

export const demoChatRooms: TradeChatRoom[] = [
  {
    id: "chat-room-trade-005",
    tradeId: "trade-005",
    status: "active",
    createdAt: "2026-06-06T19:00:00.000Z",
    updatedAt: "2026-06-06T19:05:00.000Z",
  },
  {
    id: "chat-room-trade-006",
    tradeId: "trade-006",
    status: "active",
    createdAt: "2026-06-06T20:20:00.000Z",
    updatedAt: "2026-06-06T20:32:00.000Z",
  },
  {
    id: "chat-room-trade-003",
    tradeId: "trade-003",
    status: "disputed",
    createdAt: "2026-06-05T11:35:00.000Z",
    updatedAt: "2026-06-06T13:20:00.000Z",
  },
];

export const demoChatMessages: TradeChatMessage[] = [
  {
    id: "chat-message-001",
    roomId: "chat-room-trade-005",
    tradeId: "trade-005",
    senderPiUsername: "system",
    senderRole: "system",
    messageType: "system",
    body: "Secure trade room opened after buyer funding. Use this chat for courier updates and proof.",
    createdAt: "2026-06-06T19:00:00.000Z",
  },
  {
    id: "chat-message-002",
    roomId: "chat-room-trade-005",
    tradeId: "trade-005",
    senderUserId: "buyer-user-003",
    senderPiUsername: "abuja_tradehub",
    senderRole: "buyer",
    messageType: "text",
    body: "Payment is locked. Please upload the packed lens photo before courier pickup.",
    createdAt: "2026-06-06T19:03:00.000Z",
  },
  {
    id: "chat-message-003",
    roomId: "chat-room-trade-005",
    tradeId: "trade-005",
    senderUserId: "sandbox-user-001",
    senderPiUsername: "lagos_phone_hub",
    senderRole: "seller",
    messageType: "text",
    body: "Confirmed. I will add package proof here once the courier scans it.",
    createdAt: "2026-06-06T19:05:00.000Z",
  },
  {
    id: "chat-message-004",
    roomId: "chat-room-trade-006",
    tradeId: "trade-006",
    senderPiUsername: "system",
    senderRole: "system",
    messageType: "system",
    body: "Secure trade room opened after buyer funding. Keep seller proof and buyer receipt notes here for admin release review.",
    createdAt: "2026-06-06T20:20:00.000Z",
  },
  {
    id: "chat-message-005",
    roomId: "chat-room-trade-006",
    tradeId: "trade-006",
    senderUserId: "seller-user-002",
    senderPiUsername: "market_runner",
    senderRole: "seller",
    messageType: "text",
    body: "Dispatch proof is already uploaded. Waiting for final admin release review.",
    createdAt: "2026-06-06T20:24:00.000Z",
  },
  {
    id: "chat-message-006",
    roomId: "chat-room-trade-006",
    tradeId: "trade-006",
    senderUserId: "sandbox-user-001",
    senderPiUsername: "lagos_phone_hub",
    senderRole: "buyer",
    messageType: "text",
    body: "Receipt is confirmed on my side. Admin can release the held escrow to the seller.",
    createdAt: "2026-06-06T20:32:00.000Z",
  },
  {
    id: "chat-message-007",
    roomId: "chat-room-trade-003",
    tradeId: "trade-003",
    senderPiUsername: "system",
    senderRole: "system",
    messageType: "system",
    body: "Dispute opened by @portharcourt_pi: uploaded invoice details need admin review.",
    createdAt: "2026-06-06T13:00:00.000Z",
  },
  {
    id: "chat-message-008",
    roomId: "chat-room-trade-003",
    tradeId: "trade-003",
    senderUserId: "buyer-user-002",
    senderPiUsername: "portharcourt_pi",
    senderRole: "buyer",
    messageType: "text",
    body: "The serial number on the proof does not match the part I expected.",
    createdAt: "2026-06-06T13:03:00.000Z",
  },
  {
    id: "chat-message-009",
    roomId: "chat-room-trade-003",
    tradeId: "trade-003",
    senderUserId: "buyer-user-001",
    senderPiUsername: "pi_buyer_demo",
    senderRole: "seller",
    messageType: "text",
    body: "I can upload a clearer photo and shop receipt for admin review.",
    createdAt: "2026-06-06T13:08:00.000Z",
  },
];
