import type { Trade, TradeEvent, TradeInterest } from "@/types/trade";

export const demoUser = {
  uid: "sandbox-user-001",
  username: "lagos_phone_hub",
};

export const demoTrades: Trade[] = [
  {
    id: "trade-001",
    sellerPiUsername: "lagos_phone_hub",
    sellerUserId: "sandbox-user-001",
    visibility: "public",
    targetBuyerPiUsernames: [],
    title: "Used Android phone barter",
    description:
      "Seller posted a clean used Android phone with charger and local pickup terms.",
    amountTestPi: 42,
    status: "Draft",
    interestCount: 2,
    locationLabel: "Ikeja, Lagos",
    locationArea: "Computer Village",
    deliveryTerms:
      "Seller will meet buyer at the agreed pickup point and share a photo of the packaged device before handoff.",
    createdAt: "2026-06-06T17:00:00.000Z",
    updatedAt: "2026-06-06T17:15:00.000Z",
  },
  {
    id: "trade-002",
    sellerPiUsername: "market_runner",
    sellerUserId: "seller-user-002",
    visibility: "public",
    targetBuyerPiUsernames: [],
    buyerPiUsername: "pi_buyer_demo",
    buyerUserId: "buyer-user-001",
    title: "Groceries delivery bundle",
    description:
      "Public seller offer for a grocery bundle with local delivery.",
    amountTestPi: 8.5,
    status: "PendingFunding",
    selectedInterestId: "interest-003",
    interestCount: 1,
    locationLabel: "Lekki Phase 1, Lagos",
    locationArea: "Estate gate",
    deliveryTerms:
      "Seller will deliver to the buyer's estate gate and upload a delivery note.",
    createdAt: "2026-06-06T15:30:00.000Z",
    updatedAt: "2026-06-06T16:20:00.000Z",
  },
  {
    id: "trade-003",
    sellerPiUsername: "pi_buyer_demo",
    sellerUserId: "buyer-user-001",
    visibility: "public",
    targetBuyerPiUsernames: [],
    buyerPiUsername: "portharcourt_pi",
    buyerUserId: "buyer-user-002",
    selectedInterestId: "interest-004",
    title: "Laptop repair deposit",
    description:
      "Repair technician is waiting for parts and the buyer opened a dispute until proof arrives.",
    amountTestPi: 18,
    status: "Disputed",
    interestCount: 1,
    locationLabel: "Port Harcourt, Rivers",
    locationArea: "GRA service desk",
    deliveryProofNote: "Seller uploaded a parts invoice, but the buyer says the serial number does not match.",
    deliveryProofUrl: "https://example.com/piscrow-demo-parts-proof",
    deliveryTerms:
      "Technician must upload photo evidence of the replacement part and repair receipt.",
    createdAt: "2026-06-05T11:00:00.000Z",
    updatedAt: "2026-06-06T13:00:00.000Z",
  },
  {
    id: "trade-004",
    sellerPiUsername: "market_runner",
    sellerUserId: "seller-user-002",
    visibility: "private",
    targetBuyerPiUsernames: ["lagos_phone_hub"],
    title: "Private spare parts offer",
    description:
      "A private offer only visible to selected buyers for phone spare parts.",
    amountTestPi: 15,
    status: "Draft",
    interestCount: 0,
    locationLabel: "Yaba, Lagos",
    locationArea: "Phone accessories lane",
    deliveryTerms:
      "Buyer confirms exact model before seller ships the parts locally.",
    createdAt: "2026-06-06T18:00:00.000Z",
    updatedAt: "2026-06-06T18:00:00.000Z",
  },
];

export const demoInterests: TradeInterest[] = [
  {
    id: "interest-001",
    tradeId: "trade-001",
    buyerUserId: "buyer-user-001",
    buyerPiUsername: "pi_buyer_demo",
    responseNote: "I can pay fast and pick up after work today.",
    status: "Selected",
    createdAt: "2026-06-06T16:40:00.000Z",
    updatedAt: "2026-06-06T16:50:00.000Z",
  },
  {
    id: "interest-002",
    tradeId: "trade-001",
    buyerUserId: "buyer-user-003",
    buyerPiUsername: "abuja_tradehub",
    responseNote: "I need same-day handoff and can meet near the station.",
    status: "Open",
    createdAt: "2026-06-06T16:45:00.000Z",
    updatedAt: "2026-06-06T16:45:00.000Z",
  },
  {
    id: "interest-003",
    tradeId: "trade-002",
    buyerUserId: "buyer-user-004",
    buyerPiUsername: "pi_buyer_demo",
    responseNote: "I can confirm gate pickup and handle local delivery.",
    status: "Selected",
    createdAt: "2026-06-06T15:50:00.000Z",
    updatedAt: "2026-06-06T16:00:00.000Z",
  },
  {
    id: "interest-004",
    tradeId: "trade-003",
    buyerUserId: "buyer-user-002",
    buyerPiUsername: "portharcourt_pi",
    responseNote: "I can pay today but need proof of parts before release.",
    status: "Selected",
    createdAt: "2026-06-05T11:20:00.000Z",
    updatedAt: "2026-06-05T11:25:00.000Z",
  },
];

export const demoEvents: TradeEvent[] = [
  {
    id: "event-001",
    tradeId: "trade-001",
    actor: "lagos_phone_hub",
    eventType: "Seller posted public listing",
    notes: "Seller opened the trade to public interest.",
    createdAt: "2026-06-06T16:00:00.000Z",
  },
  {
    id: "event-002",
    tradeId: "trade-001",
    actor: "pi_buyer_demo",
    eventType: "Interest submitted",
    notes: "Buyer responded with same-day pickup availability.",
    createdAt: "2026-06-06T16:40:00.000Z",
  },
  {
    id: "event-003",
    tradeId: "trade-002",
    actor: "market_runner",
    eventType: "Private offer finalized",
    notes: "Seller limited the listing to selected buyers.",
    createdAt: "2026-06-06T15:35:00.000Z",
  },
  {
    id: "event-004",
    tradeId: "trade-001",
    actor: "lagos_phone_hub",
    eventType: "Buyer selected",
    notes: "Seller chose the buyer response with the best pickup plan.",
    createdAt: "2026-06-06T16:50:00.000Z",
  },
  {
    id: "event-005",
    tradeId: "trade-001",
    actor: "pi_buyer_demo",
    eventType: "Trade funded",
    notes: "Server verified buyer Test Pi payment.",
    createdAt: "2026-06-06T17:15:00.000Z",
  },
  {
    id: "event-006",
    tradeId: "trade-002",
    actor: "market_runner",
    eventType: "Delivery submitted",
    notes: "Seller uploaded delivery note for buyer review.",
    createdAt: "2026-06-06T16:20:00.000Z",
  },
  {
    id: "event-007",
    tradeId: "trade-003",
    actor: "portharcourt_pi",
    eventType: "Dispute opened",
    notes: "Buyer requested admin review before completion.",
    createdAt: "2026-06-06T13:00:00.000Z",
  },
];
